supporting macosx (not including safari)
alifcommunity/webui pull request #10
Opened 2021-03-22 17:15 UTC by usama-makhzoum

2021-03-26 01:18 UTC, hassandraga requested changes

2021-03-26 01:18 UTC, hassandraga commented on src/webui.cpp
> +				std::cout << browser::browser_path + " -CreateProfile \"WebUI " + temp + webui::sep + profile_name + "\"" << std::endl;
كنت تستعمل هدا السطر لرأية النتيجة، ربمى نسيت إزالته الآن!
إن كنت تحتاج تتبيث "ديبوغ" فراسلني
شكرا لك

2021-03-28 03:18 UTC, hassandraga commented on src/webui.cpp
> +				std::cout << browser::browser_path + " -CreateProfile \"WebUI " + temp + webui::sep + profile_name + "\"" << std::endl;
هل تفظل أن أقوم بعمل
merge
ثم أزيل هذا السطر، أم أنتظر ؟

2021-03-28 16:55 UTC, usama-makhzoum commented on src/webui.cpp
> +				std::cout << browser::browser_path + " -CreateProfile \"WebUI " + temp + webui::sep + profile_name + "\"" << std::endl;
ادمج 
لكن لا تزيل السطر بل اعمل له تعليق، هذا أسلوب دارج في المشاريع البرمجية بشكل عام

2021-03-29 23:42 UTC, merged

2021-03-29 23:44 UTC, hassandraga commented on src/webui.cpp
> +				std::cout << browser::browser_path + " -CreateProfile \"WebUI " + temp + webui::sep + profile_name + "\"" << std::endl;
شكرا لك أخ أسامة